### ISSUE TITLE
Can't install with "composer require"

### ISSUE THREAD

**Issue by gbirke** [researchgate/converter#10]
I have tried to install the library with `composer require`, as instructed by the README. However, I got the following error message:

```
Using version ^1.2 for researchgate/converter
./composer.json has been updated
Running composer update researchgate/converter
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires researchgate/converter ^1.2 -> satisfiable by researchgate/converter[1.2.0].
    - researchgate/converter 1.2.0 requires researchgate/libris ^2.3.0 -> could not be found in any version, there may be a typo in the package name.
```

I can see that `researchgate/libris` is not published on packagist.org

I have tried to circumvent the error by adding the following section to my `composer.json`:

```
"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/researchgate/libris.git"
    }
  ]
```

This made the `require` command work, however while installing I got the following error messages:

```
Skipped branch 1.x, "9ea2294ae906b8f855ae53cde7a1ef0e5e09dc90:composer.json" does not contain valid JSON
Parse error on line 8:
...ersion": "1.1.2"  "requires": {    "p
--------------------^
Expected one of: 'EOF', '}', ':', ',', ']'

Info from https://repo.packagist.org: #StandWithUkraine
Using version ^1.2 for researchgate/converter
./composer.json has been updated
Running composer update researchgate/converter
Loading composer repositories with package information
                                                      
Skipped branch 1.x, "9ea2294ae906b8f855ae53cde7a1ef0e5e09dc90:composer.json" does not contain valid JSON
Parse error on line 8:
...ersion": "1.1.2"  "requires": {    "p
--------------------^
Expected one of: 'EOF', '}', ':', ',', ']'
```

**Comment by mdio** [comment]
Sorry for the late reply, this fell under the radar.
I've fixed the broken composer.json for libris 1.x and I will see about getting libris into packagist.
I'll report back next week.

**Comment by mdio** [comment]
Unfortunately the composer namespace `researchgate/` is owned by a former employee of RG, so can't publish `researchgate/libris`, yet.
I've asked them to transfer ownership to us. Once that is done I'll publish libris and this should work.

**Comment by mdio** [comment]
Now that we have ownership, libris has been published and I've removed the now obsolete repository reference to it from the composer.json (PR #12).
I've also verified that require works now without having to specify the URL to the libris repository.
